name: Release Authentication Adapters Package

on:
  workflow_dispatch:
    inputs:
      Version:
        description: "This input field requires version in format: x.y.z, where x => major version, y => minor version and z => patch version"
        required: true

jobs:
  build:
    name: Build and publish Authentication Adapters Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 19.x
        uses: actions/setup-node@v1
        with:
          node-version: "19.x"

      - name: Install dependencies and build
        run: |
          yarn install --frozen-lockfile
          yarn run build

      - name: Bump authentication-adapters version
        run: |
          cd packages/authentication-adapters
          yarn version --no-git-tag-version --new-version ${{ github.event.inputs.Version }}

      - name: Release to npm
        id: release
        run: |
          cd packages/authentication-adapters 
          npm publish --@myscope:registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit the version change
        if: steps.release.outputs.exit_code == 0
        uses: devops-infra/action-commit-push@master
        with:
            github_token: "${{ secrets.GITHUB_TOKEN }}"
            commit_message: "ci(authentication-adapters): update package version"
            force: false
            target_branch: project-version-update

      - name: Push the version change
        if: steps.release.outputs.exit_code == 0
        uses: CasperWA/push-protected@v2
        with:
            # token: ${{ secrets.PAT }}
            token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref_name }}

      - name: Delete the intermediate branch
        if: steps.release.outputs.exit_code == 0
        run: |
            git branch -D project-version-update &>/dev/null || true
            git push origin :project-version-update &>/dev/null || true

      - name: Create tag
        if: steps.release.outputs.exit_code == 0
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          # github_token: ${{ secrets.PAT }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ github.event.inputs.Version }}
          tag_prefix: ""

      - name: Create changelog for the release
        if: steps.release.outputs.exit_code == 0
        uses: ncipollo/release-action@v1
        with: 
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release Authentication Adapters Version ${{ github.event.inputs.Version }}
          body: ${{ steps.tag_version.outputs.changelog }}

      # - name: Send slack notification
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.25.0
      #   with:
      #     channel-id: 'C012YFE3D6D'
      #     slack-message: "core-lib-java release has been triggered!"
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
